// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config = {
  "aws_appsync_graphqlEndpoint":
    "https://2ptugwt4lrgffgrrjmjys6dodm.appsync-api.ap-south-1.amazonaws.com/graphql",
  "aws_appsync_region":  "ap-south-1",
  "aws_appsync_authenticationType": "apiKey",
  "aws_appsync_apiKey": "da2-5hceo6ce7jdhffgy2t2n2zyjam",
};


export default config;
